version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    # ...
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: Install Python Dependencies
          command: |  # use pipenv to install dependencies
            pip install --user -r reuirements.txt
            python3 create_ec2.py
            
            
            
            
            
            
