version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: sudo apt update
      - run: sudo apt install python-pip
      - run: sudo apt-get install software-properties-common
      - run: sudo add-apt-repository ppa:deadsnakes/ppa
      - run: sudo apt-get update
      - run: sudo apt-get install python3.6
      - run: sudo apt install python3-pip
      - run: 
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt


