version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run: sudo pip install -r requirements/dev.txt
      - run: pwd
      - run: python ~/project/python/flask_site/flaskblog.py