- hosts: app
  tasks:
    - name: Create a directory if it does not exist
      file:
        path: /home/ahorne/app/flaskblog
        state: directory
        mode: '0755'
    - name: Create a directory if it does not exist
      file:
        path: /home/ahorne/app/flaskblog/static/profile_pics
        state: directory
        mode: '0755'
    - name:
      copy:
        src: /Users/ahorne/flask_centos/flaskblog/forms.py
        dest: /home/ahorne/app/flaskblog
        owner: ahorne
        mode: '0644'
    - name:
      copy:
        src: /Users/ahorne/flask_centos/flaskblog/models.py
        dest: /home/ahorne/app/flaskblog
        owner: ahorne
        mode: '0644'
    - name:
      copy:
        src: /Users/ahorne/flask_centos/flaskblog/routes.py
        dest: /home/ahorne/app/flaskblog
        owner: ahorne
        mode: '0644'
    - name: __init__ main 
      copy:
        src: /Users/ahorne/flask_centos/flaskblog/__init__.py
        dest: /home/ahorne/app/flaskblog
        owner: ahorne
        mode: '0644'
    - name: account.html 
      copy:
        src: /Users/ahorne/flask_centos/templates/account.html
        dest: /home/ahorne/app//flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: account.html 
      copy:
        src: /Users/ahorne/flask_centos/static/profile_pics/default.jpg
        dest: /home/ahorne/app//flaskblog/static/profile_pics/
        owner: ahorne
        mode: '0644'
    #- name:
    #  copy:
    #    src: /Users/ahorne/flask_centos/flaskblog/site.db
    #    dest: /home/ahorne/app/flaskblog
    #    owner: ahorne
    #    mode: '0644'
    - name: templates home.html
      copy:
        src:  /Users/ahorne/flask_centos/templates/home.html
        dest: /home/ahorne/app/flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: static main.css
      copy:
        src:  /Users/ahorne/flask_centos/static/main.css
        dest: /home/ahorne/app/flaskblog/static/main.css
        owner: ahorne
        mode: '0644'
    - name: templates about.html 
      copy:
        src:  /Users/ahorne/flask_centos/templates/about.html
        dest: /home/ahorne/app/flaskblog/templates/about.html
        owner: ahorne
        mode: '0644'
    - name: templates about.html 
      copy:
        src:  /Users/ahorne/flask_centos/templates/post.html
        dest: /home/ahorne/app/flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: templates layout.html
      copy:
        src:  /Users/ahorne/flask_centos/templates/layout.html
        dest: /home/ahorne/app/flaskblog/templates/layout.html
        owner: ahorne
        mode: '0644'
    - name: templates layout.html
      copy:
        src:  /Users/ahorne/flask_centos/templates/create_post.html
        dest: /home/ahorne/app/flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: login.html
      copy:
        src: /Users/ahorne/flask_centos/templates/login.html
        dest: /home/ahorne/app/flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: register.html
      copy:
        src: /Users/ahorne/flask_centos/templates/register.html
        dest: /home/ahorne/app/flaskblog/templates/
        owner: ahorne
        mode: '0644'
    - name: run.py
      copy:
        src: /Users/ahorne/flask_centos/run.py
        dest: /home/ahorne/app
        owner: ahorne
        mode: '0644'
    - name: Remove file (delete file)
      file:
        path: /home/ahorne/app/app.py
        state: absent
    - name: Remove file (delete file)
      file:
        path: /home/ahorne/app/site.db
        state: absent
    - name: Remove file (delete file)
      file:
        path: /home/ahorne/app/forms.py
        state: absent
    - name: Remove file (delete file)
      file:
        path: /home/ahorne/app/templates/layouts.html
        state: absent
    - name: Remove file (delete file)
      file:
        path: /home/ahorne/app/models.py
        state: absent
    - name: run server
      shell: python3 run.py
      args:
        chdir: /home/ahorne/app/
